apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        #- image: docker.io/vadimkharincodefresh/rollouts-demo:purple@sha256:7eb247cd551178b7b27f93d2efeea0ac314f63947b201441c2256652270dfce4
        #- image: docker.io/vadimkharincodefresh/rollouts-demo:yellow@sha256:85497f05d51e94181e08a4ad0cfe702cf23f060cc46028b9011d86c4b7bb03fa
        - image: docker.io/vadimkharincodefresh/rollouts-demo:purple
        #- image: docker.io/vadimkharincodefresh/rollouts-demo@sha256:85497f05d51e94181e08a4ad0cfe702cf23f060cc46028b9011d86c4b7bb03fa
          name: guestbook-ui
          ports:
            - containerPort: 80
