apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: idanarbel/rollouts-demo@sha256:f448eb2be435d0466117acd0162be0e646bc8d4475ce804a8070043f689f4c3d
          name: guestbook-ui
          ports:
            - containerPort: 80
