apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: docker.io/vadimkharincodefresh/rollouts-demo@sha256:75ae224f1e8f73dbbe4fc44eb11be6065d21d3b71d7ddfff9581cb0dd06c3efb
          name: guestbook-ui
          ports:
            - containerPort: 80
